#!/bin/bash


#
# Utility script to configure or control the temperature on Odroid xu3/xu4 board.
#
# Usage: fanctl [-d] [-q] [-r] [-p period] [-m mode]
#               [-s fan states] [-f freq states] [-t temperature limits]
#
#        -d Debug output.
#        -q Query automatic mode temperature control and fan settings.
#        -r Monitor temperature, fan speed and cpu frequency.
#        -p Update period for manual temperature control and monitoring.
#        -m Set fan control mode (0 - manual, 1 - automatic).
#        -s Set fan speed states in % of maximum (0 - 100). Format is "S1,S2,S3,S4".
#        -f Set maximum cpu frequency states in MHz. Format is "S1,S2,S3,S4".
#        -t Set fan temperature limits in degrees C. Format is "T1,T2,T3".
#
# Temperature control via fan control (in both manual and automatic mode)
# works by setting the fan speed to one of four states (S1, S2, S3, S4)
# depending on the current temperature and temperature limits (T1, T2, T3).
# The relationship between fan speed (S) and temperature (T) in auto mode is:
#
# T < T1        S => S1
# T1 < T < T2   S => S2
# T2 < T < T3   S => S3
# T3 < T        S => S4
#
# The temperature control has two operating modes, manual and automatic.
#
# In manual mode the hardware will simply spin the fan with a constant speed.
# However the control loop is run by this script. The behavior is exactly
# the same as the behavior of hardware temperature control in automatic mode.
# After the script terminates it will always set the control mode to automatic
# to minimize the possibility of overheating. If this mode is specified
# the script will run the control loop indefinitely.
#
# In manual mode the control loop is performed by this utility. After the
# utility terminates it will always set the control mode to automatic to
# minimize the possibility of overheating. If this mode is specified the
# script will run the control loop indefinitely.
#
# In manual mode it is possible to run the a temperature control loop that
# modifies the maximum cpu frequency instead of fan speed. The behavior is
# analogous to the that of fan speed based control only that the fan speed
# states are replaced by maximum cpu frequency states. In this mode the
# maximum frequency of all cores is modified.
#
# The script can also periodically display the current fan speed, temperature
# and cpu frequency.
#


# Constants.
readonly FAN_MODE_MANUAL="0"
readonly FAN_MODE_AUTO="1"
readonly CPU_FREQ_MAX="2000"

# Command line arguments.
readonly ARGS="$@"

# Parsed command line arguments.
FAN_MODE=""
FAN_SPEEDS=""
CPU_FREQS=""
TEMP_LIMITS=""
PERIOD="1"
QUERY="false"
MONITOR="false"
DEBUG="false"

# Temperature control related device node files.
readonly FAN_FOLDER_XU3="/sys/devices/odroid_fan.14"
readonly FAN_FOLDER_XU4="/sys/devices/odroid_fan.13"
FAN_FOLDER=""
CORE_TEMP_FILE=""
FAN_MODE_FILE=""
FAN_SPEEDS_FILE=""
FAN_PWM_FILE=""
TEMP_LIMITS_FILE=""


################################################################################


printf_err () {
    printf "ERROR: %-16s %s \n" "[${FUNCNAME[1]}]:" "$@" >&2
}


printf_dbg () {
    if [[ "$DEBUG" == "true" ]]; then
        printf "DEBUG: %-16s %s \n" "[${FUNCNAME[1]}]:" "$@"
    fi
}


################################################################################


cmdline () {
    while getopts ":m:s:f:t:p:qrd" opt; do
        case $opt in
            m)
                FAN_MODE="$OPTARG"
                ;;
            s)
                FAN_SPEEDS="$OPTARG"
                ;;
            f)
                CPU_FREQS="$OPTARG"
                ;;
            t)
                TEMP_LIMITS="$OPTARG"
                ;;
            p)
                PERIOD="$OPTARG"
                ;;
            q)
                QUERY="true"
                ;;
            r)
                MONITOR="true"
                ;;
            d)
                DEBUG="true"
                ;;
            \?)
                printf "invalid option: -%c \n" "$OPTARG" >&2
                exit 1
                ;;
            :)
                printf "option -%c requires an argument \n" "$OPTARG" >&2
                exit 1
                ;;
        esac
    done

    readonly FAN_MODE
    readonly FAN_SPEEDS
    readonly CPU_FREQS
    readonly TEMP_LIMITS
    readonly PERIOD
    readonly QUERY
    readonly MONITOR
    readonly DEBUG
}


################################################################################


check_board () {
    if [[ -d "$FAN_FOLDER_XU4" ]]; then
        FAN_FOLDER="$FAN_FOLDER_XU4"
        printf_dbg "odroid-xu4 board"
    elif [[ -d "$FAN_FOLDER_XU3" ]]; then
        FAN_FOLDER="$FAN_FOLDER_XU3"
        printf_dbg "odroid-xu3 board"
    else
        printf_err "unsupported board"
        exit 1
    fi

    CORE_TEMP_FILE="/sys/devices/virtual/thermal/thermal_zone0/temp"
    FAN_MODE_FILE="$FAN_FOLDER/fan_mode"
    FAN_SPEEDS_FILE="$FAN_FOLDER/fan_speeds"
    FAN_PWM_FILE="$FAN_FOLDER/pwm_duty"
    TEMP_LIMITS_FILE="$FAN_FOLDER/temp_levels"

    if [[ ! (  -e "$FAN_MODE_FILE"
            && -e "$FAN_SPEEDS_FILE"
            && -e "$FAN_PWM_FILE"
            && -e "$TEMP_LIMITS_FILE"
            && -e "$CORE_TEMP_FILE" ) ]]
    then
        printf_err "device node files not present"
        exit 1
    fi

    readonly FAN_FOLDER
    readonly CORE_TEMP_FILE
    readonly FAN_MODE_FILE
    readonly FAN_SPEEDS_FILE
    readonly FAN_PWM_FILE
    readonly TEMP_LIMITS_FILE
}


################################################################################


check_cmdline () {
    if [[ -n "$FAN_MODE" ]]; then

        check_mode

        # In auto mode it is possible to to set either temperature limits, fan
        # speed states, both or none (meaning just switching to auto mode and
        # using whatever values are currently set).
        if [[ "$FAN_MODE" == "$FAN_MODE_AUTO" ]]; then
            if [[ -n "$CPU_FREQS" ]]; then
                printf_err "only control via fan speed is possible in auto mode"
                exit 1
            fi

            if [[ -n "$TEMP_LIMITS" ]]; then
                check_temps
            fi

            if [[ -n "$FAN_SPEEDS" ]]; then
                check_speeds
            fi
        fi

        # In manual mode (where this script runs the control loop) the
        # temperature limits and exactly one of either fan speed states or
        # cpu frequency limits have to be set.
        if [[ "$FAN_MODE" == "$FAN_MODE_MANUAL" ]]; then
            if [[ -z "$TEMP_LIMITS" ]]; then
                printf_err "temperature limits need to be specified in manual mode"
                exit 1
            fi

            check_temps

            if [[ ( -n "$FAN_SPEEDS" && -n "$CPU_FREQS" )
                    || ( -z "$FAN_SPEEDS" && -z "$CPU_FREQS" ) ]]
            then
                printf_err "exactly one control method has to be specified in manual mode"
                exit 1
            fi

            if [[ -n "$FAN_SPEEDS" ]]; then
                check_speeds
            fi

            if [[ -n "$CPU_FREQS" ]]; then
                check_freqs
            fi
        fi

    else
        if [[ -n "$TEMP_LIMITS" || -n "$FAN_SPEEDS" || -n "$CPU_FREQS" ]]; then
            printf_err "fan control mode needs to be specified"
            exit 1
        fi
    fi
}


check_mode () {
    if [[ "$FAN_MODE" != "$FAN_MODE_AUTO"
            && "$FAN_MODE" != "$FAN_MODE_MANUAL" ]];
    then
        printf_err "invalid control mode: $FAN_MODE"
        exit 1
    fi

    printf_dbg "control mode valid: $FAN_MODE"
}


check_temps () {
    if [[ ! "$TEMP_LIMITS" =~ ^[0-9]+,[0-9]+,[0-9]+$ ]]; then
        printf_err "invalid temperature limits: $TEMP_LIMITS"
        exit 1
    fi

    printf_dbg "temperature limits valid: $TEMP_LIMITS"
}


check_speeds () {
    if [[ ! "$FAN_SPEEDS" =~ ^[0-9]+,[0-9]+,[0-9]+,[0-9]+$ ]]; then
        printf_err "invalid fan speeds: $FAN_SPEEDS"
        exit 1
    fi

    local fan_speeds_array=(${FAN_SPEEDS//,/ })
    local fan_speed=""

    for i in ${!fan_speeds_array[@]}; do
        fan_speed=${fan_speeds_array[i]}
        if (( fan_speed > 255 )); then
            printf_err "invalid fan speed: $fan_speed"
            exit 1
        fi
    done

    printf_dbg "fan speed states valid: $FAN_SPEEDS"
}


check_freqs () {
    if [[ ! "$CPU_FREQS" =~ ^[0-9]+,[0-9]+,[0-9]+,[0-9]+$ ]]; then
        printf_err "invalid cpu frequencies: $CPU_FREQS"
        exit 1
    fi

    printf_dbg "cpu frequencies valid: $CPU_FREQS"
}


################################################################################


config_mode () {
    printf_dbg "setting fan control mode: $FAN_MODE"
    printf "$FAN_MODE" > "$FAN_MODE_FILE"
}


config_temps () {
    local temp_limits="${TEMP_LIMITS//,/ }"
    printf_dbg "setting auto mode temperature limits: $temp_limits"
    printf "$temp_limits" > "$TEMP_LIMITS_FILE"
}


config_speeds () {
    local fan_speeds="${FAN_SPEEDS//,/ }"
    printf_dbg "setting auto mode fan speed states: $fan_speeds"
    printf "$fan_speeds" > "$FAN_SPEEDS_FILE"
}


control_temp () {
    local method="$1"
    local states=""

    if [[ "$method" == "fan" ]]; then
        states="$FAN_SPEEDS"
        state_setter="set_fan_speed"
    elif [[ "$method" == "freq" ]]; then
        states="$CPU_FREQS"
        state_setter="set_cpu_freq"
    else
        printf_err "invalid control method: $method"
        exit 1
    fi

    printf_dbg "control method: $method"

    local temp_limits_array=(${TEMP_LIMITS//,/ })
    local temp_limit_max=1000
    local temp_limit=""

    local states_array=(${states//,/ })
    local state_value=""

    local core_temp=""

    # Add forth temperature limit that is high enough to always be higher than
    # the current temperature.
    temp_limits_array[${#temp_limits_array[@]}]="$temp_limit_max"

    if [[ "$MONITOR" == "true" ]]; then
        monitor_header
    fi

    # Main temperature control loop.
    while true; do
        core_temp="$(cat $CORE_TEMP_FILE | sed -r "s:[0-9]{3}$::")"

        for i in ${!temp_limits_array[@]}; do
            temp_limit="${temp_limits_array[i]}"
            state_value="${states_array[i]}"
            if (( core_temp < temp_limit )); then
                if [[ "$MONITOR" == "true" ]]; then
                    get_status
                fi
                "$state_setter" "$state_value"
                break
            fi
        done

        sleep "$PERIOD"
    done
}


set_fan_speed () {
    local fan_speed="$1"
    local fan_pwm="$(( $fan_speed * 255 / 100 ))"

    printf_dbg "setting fan speed (pwm): $fan_speed ($fan_pwm)"
    printf "$fan_pwm" > "$FAN_PWM_FILE"
}


set_cpu_freq () {
    local cpu_freq_mhz="$1"
    local cpu_freq_khz="$(( $1 * 1000 ))"

    printf_dbg "setting max cpu frequency: $cpu_freq_mhz MHz"
    cpupower -c all frequency-set -u "$cpu_freq_khz" 1>/dev/null
}


get_config () {
    local fan_mode="$(cat $FAN_MODE_FILE | sed "s:fan_mode ::")"
    local fan_speeds="$(cat $FAN_SPEEDS_FILE)"
    local temp_limits="$(cat $TEMP_LIMITS_FILE)"

    printf "Fan control mode:             %s \n" "$fan_mode"
    printf "Auto speed settings [%%]:      %s \n" "$fan_speeds"
    printf "Auto temperature limits [C]:  %s \n" "$temp_limits"
}


get_status () {
    local core_temp="$(cat $CORE_TEMP_FILE | sed -r "s:[0-9]{3}$::")"
    local fan_pwm="$(cat $FAN_PWM_FILE)"
    local fan_speed="$(( fan_pwm * 100 / 255 ))"
    local cpu_freq_a7="$(cpupower -c 0 frequency-info -f  \
            | tail -n 1                             \
            | sed -r 's:[0-9]{3}$::')"
    local cpu_freq_a15="$(cpupower -c 4 frequency-info -f \
            | tail -n 1                             \
            | sed -r 's:[0-9]{3}$::')"

    printf "%4d MHz " "$cpu_freq_a15"
    printf "%4d MHz " "$cpu_freq_a7"
    printf "%3d C " "$core_temp"
    printf "%3d %% " "$fan_speed"
    printf "\n"
}


monitor_header () {
    printf " A15       A7      TEMP   FAN \n"
    printf "******************************\n"
}


monitor_status () {
    monitor_header
    while true; do
        get_status
        sleep "$PERIOD"
    done
}


################################################################################


before_exit () {
    printf_dbg "setting automatic fan control mode"
    printf "$FAN_MODE_AUTO" > "$FAN_MODE_FILE"

    printf_dbg "removing cpu frequency limits"
    set_cpu_freq "$CPU_FREQ_MAX"
}


################################################################################


main () {
    check_board
    cmdline $ARGS
    check_cmdline

    if [[ "$QUERY" == "true" ]]; then
        get_config
    fi

    if [[ "$FAN_MODE" == "$FAN_MODE_AUTO" ]]; then
        config_mode

        if [[ -n "$TEMP_LIMITS" ]]; then
            config_temps
        fi

        if [[ -n "$FAN_SPEEDS" ]]; then
            config_speeds
        fi
    fi

    if [[ "$FAN_MODE" == "$FAN_MODE_MANUAL" ]]; then
        trap before_exit EXIT

        config_mode

        if [[ -n "$FAN_SPEEDS" ]]; then
            control_temp "fan"
        fi

        if [[ -n "$CPU_FREQS" ]]; then
            set_fan_speed "0"
            control_temp "freq"
        fi
    fi

    if [[ "$MONITOR" == "true" ]]; then
        monitor_status
    fi
}


main
